from __future__ import annotations

from .constants import GENERIC_DEMO_URL
from .models import PreviewMenu, TicketMachineHint


def build_pitch(
    *,
    business_name: str,
    category: str,
    preview_menu: PreviewMenu,
    ticket_machine_hint: TicketMachineHint | None,
    recommended_package: str,
) -> dict[str, dict[str, str]]:
    """Legacy-only compatibility wrapper.

    Active first-contact outreach is generated by ``pipeline.outreach``.
    This wrapper remains for older callers that still expect a ``pitch_draft``
    dict, but it deliberately returns generic QR-first copy without any
    lead-specific sample/menu claims.
    """

    subject = f"{business_name}様 — 英語QRメニューのご案内"
    body = (
        f"{business_name}様\n\n"
        f"初めてご連絡いたします。WebRefurbのChris（クリス）です。\n\n"
        f"日本語メニューはそのまま使い、お客様がQRコードを読み取ってスマートフォンで英語メニューを確認できる形を制作しています。\n"
        f"お客様は気になる料理をリストに追加し、最後に日本語の商品名・数量・選択肢が並んだShow Staff Listをスタッフの方に見せることができます。\n\n"
        f"汎用デモはこちらです：\n{GENERIC_DEMO_URL}\n\n"
        f"もし貴店でも役立ちそうでしたら、ご返信ください。\n\n"
        f"よろしくお願いいたします。\n"
        f"Chris（クリス）"
    )

    return {
        "native": {"subject": subject, "body": body},
    }
