from __future__ import annotations

import hashlib
import json
import re
import shutil
import urllib.parse
import urllib.request
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Callable

from .constants import PROJECT_ROOT
from .lead_dossier import ensure_lead_dossier
from .record import persist_lead_record
from .search_scope import normalise_search_category, search_jobs_for_scope
from .utils import read_json, sha256_text, slugify, utc_now, write_json, write_text


class ReplayCorpusError(ValueError):
    """Raised when a replay corpus is missing required deterministic data."""


REQUIRED_LABEL_FIELDS = {
    "candidate_id",
    "business_name",
    "category_expected",
    "readiness_expected",
    "package_expected",
    "contact_route_expected",
    "inline_assets_expected",
    "ticket_machine_state_expected",
    "english_menu_state_expected",
    "proof_strength_minimum",
    "label_confidence",
}
LABEL_CATEGORY_VALUES = {"ramen", "izakaya", "out_of_scope"}
LABEL_READINESS_VALUES = {"ready_for_outreach", "manual_review", "disqualified"}
LABEL_PACKAGE_VALUES = {
    "package_1_remote_30k",
    "package_2_printed_delivered_45k",
    "package_3_qr_menu_65k",
    "custom_quote",
    "none",
}
LABEL_CONTACT_ROUTE_VALUES = {"email", "contact_form", "none"}
UNSUPPORTED_LABEL_CONTACT_ROUTES = {"phone", "line", "instagram", "walk_in", "website", "website_only", "map_url"}
LABEL_TICKET_MACHINE_VALUES = {"present", "absent", "unknown", "already_english_supported"}
LABEL_ENGLISH_MENU_VALUES = {"missing", "weak_partial", "image_only", "usable_complete", "unknown"}
LABEL_PROOF_VALUES = {"gold", "operator_only", "none"}
LABEL_CONFIDENCE_VALUES = {"high", "medium", "low"}

COLLECTION_SCHEMA_VERSION = 2
DEFAULT_LAUNCH_MARKETS = [
    "Shibuya",
    "Shinjuku",
    "Ikebukuro",
    "Nakano",
    "Akihabara",
    "Asakusa",
    "Ueno",
    "Namba",
    "Umeda",
    "Shinsekai",
    "Gion",
    "Kawaramachi",
    "Kyoto Station",
    "Tenjin",
    "Hakata",
    "Nakasu",
    "Susukino",
    "Sapporo Station",
    "Sakae",
    "Nagoya Station",
    "Kannai",
    "Minatomirai",
    "Yokohama Station",
    "Sannomiya",
    "Hondori",
    "Kokubuncho",
    "Nara",
    "Kanazawa",
    "Hakone",
    "Kamakura",
]


def load_replay_corpus(corpus_dir: str | Path, *, require_labels: bool = True) -> dict[str, Any]:
    """Load a deterministic search replay fixture from disk.

    The first production-simulation slice uses committed, sanitized fixture
    records instead of live Serper/search/fetch calls. This keeps replay stable
    and makes the no-send boundary explicit.
    """
    root = Path(corpus_dir)
    manifest = read_json(root / "manifest.json")
    if not isinstance(manifest, dict):
        raise ReplayCorpusError(f"missing manifest.json in {root}")

    candidates_file = root / str(manifest.get("candidates_file") or "candidates.json")
    candidates = read_json(candidates_file)
    if not isinstance(candidates, list):
        raise ReplayCorpusError(f"missing candidate list: {candidates_file}")

    labels_dir = root / str(manifest.get("labels_dir") or "labels")
    labels: dict[str, dict[str, Any]] = {}
    label_paths = sorted(labels_dir.glob("*.json")) if labels_dir.exists() else []
    for path in label_paths:
        label = read_json(path)
        if not isinstance(label, dict):
            raise ReplayCorpusError(f"invalid label JSON: {path}")
        validate_label_schema(label, label_path=path)
        candidate_id = str(label["candidate_id"])
        labels[candidate_id] = label

    candidate_ids = {candidate_id_for(candidate) for candidate in candidates}
    missing_labels = sorted(candidate_ids - set(labels))
    if require_labels and missing_labels:
        partial_labels_allowed = bool(manifest.get("labeling_workflow")) or str(manifest.get("run_scope") or "") == "pilot_broad_collection_scaffold"
        if partial_labels_allowed and labels:
            candidates = [candidate for candidate in candidates if candidate_id_for(candidate) in labels]
        else:
            raise ReplayCorpusError(f"missing labels for candidates: {missing_labels}")

    return {
        "root": root,
        "manifest": manifest,
        "candidates": candidates,
        "labels": labels,
        "unlabeled_candidate_ids": missing_labels,
    }


def validate_label_schema(label: dict[str, Any], *, label_path: str | Path | None = None) -> None:
    """Validate finalized production-simulation labels before replay.

    Drafts generated by the labeling workflow live outside the manifest
    labels directory. Anything placed directly in labels/ is treated as
    replayable ground truth, so expected-ready labels must be high confidence
    or carry an approved second-pass review.
    """
    name = Path(label_path).name if label_path else str(label.get("candidate_id") or "label")
    missing = REQUIRED_LABEL_FIELDS - set(label)
    if missing:
        raise ReplayCorpusError(f"label {name} missing fields: {sorted(missing)}")
    _assert_label_value(name, "category_expected", label.get("category_expected"), LABEL_CATEGORY_VALUES)
    _assert_label_value(name, "readiness_expected", label.get("readiness_expected"), LABEL_READINESS_VALUES)
    _assert_label_value(name, "package_expected", label.get("package_expected"), LABEL_PACKAGE_VALUES)
    _assert_label_value(name, "contact_route_expected", label.get("contact_route_expected"), LABEL_CONTACT_ROUTE_VALUES)
    _assert_label_value(name, "ticket_machine_state_expected", label.get("ticket_machine_state_expected"), LABEL_TICKET_MACHINE_VALUES)
    _assert_label_value(name, "english_menu_state_expected", label.get("english_menu_state_expected"), LABEL_ENGLISH_MENU_VALUES)
    _assert_label_value(name, "proof_strength_minimum", label.get("proof_strength_minimum"), LABEL_PROOF_VALUES)
    _assert_label_value(name, "label_confidence", label.get("label_confidence"), LABEL_CONFIDENCE_VALUES)
    if not isinstance(label.get("inline_assets_expected"), list):
        raise ReplayCorpusError(f"label {name} inline_assets_expected must be a list")

    if str(label.get("readiness_expected")) == "ready_for_outreach":
        confidence = str(label.get("label_confidence") or "")
        review = label.get("second_pass_review") if isinstance(label.get("second_pass_review"), dict) else {}
        review_status = str((review or {}).get("status") or "").strip().lower()
        review_approved = review_status in {"approved", "complete", "completed"} or (review or {}).get("approved") is True
        if confidence != "high" and not review_approved:
            raise ReplayCorpusError(
                f"label {name} expected-ready labels require label_confidence=high "
                "or approved second_pass_review"
            )


def _assert_label_value(name: str, key: str, value: Any, allowed: set[str]) -> None:
    if str(value) not in allowed:
        raise ReplayCorpusError(f"label {name} {key} must be one of {sorted(allowed)}")


def reconcile_label_contact_policy(corpus_dir: str | Path) -> dict[str, Any]:
    """Rewrite stale finalized labels so unsupported routes no longer count as ready."""
    root = Path(corpus_dir)
    manifest = read_json(root / "manifest.json")
    if not isinstance(manifest, dict):
        raise ReplayCorpusError(f"missing manifest.json in {root}")
    labels_dir = root / str(manifest.get("labels_dir") or "labels")
    changed: list[dict[str, Any]] = []
    unchanged = 0
    for path in sorted(labels_dir.glob("*.json")):
        label = read_json(path)
        if not isinstance(label, dict):
            continue
        before = json.dumps(label, sort_keys=True, ensure_ascii=False)
        route = str(label.get("contact_route_expected") or "").strip()
        if route in UNSUPPORTED_LABEL_CONTACT_ROUTES:
            label["legacy_contact_route_expected"] = route
            label["contact_route_expected"] = "none"
            label["inline_assets_expected"] = []
            notes = str(label.get("label_notes") or "").strip()
            suffix = "Reconciled to email/contact-form-only policy; unsupported outreach routes require manual review."
            label["label_notes"] = f"{notes} {suffix}".strip()
            if label.get("readiness_expected") == "ready_for_outreach":
                label["readiness_expected"] = "manual_review"
                label["rejection_reason_expected"] = "no_supported_contact_route"
                label["package_expected"] = "none"
                review = label.get("second_pass_review") if isinstance(label.get("second_pass_review"), dict) else {}
                label["second_pass_review"] = {
                    **review,
                    "required": False,
                    "status": "not_required",
                    "reason": "route policy reconciliation moved unsupported-route ready label to manual review",
                }
        elif route not in LABEL_CONTACT_ROUTE_VALUES:
            label["legacy_contact_route_expected"] = route
            label["contact_route_expected"] = "none"
            label["inline_assets_expected"] = []
            if label.get("readiness_expected") == "ready_for_outreach":
                label["readiness_expected"] = "manual_review"
                label["rejection_reason_expected"] = "no_supported_contact_route"
                label["package_expected"] = "none"

        after = json.dumps(label, sort_keys=True, ensure_ascii=False)
        if after != before:
            validate_label_schema(label, label_path=path)
            write_json(path, label)
            changed.append({
                "candidate_id": label.get("candidate_id"),
                "business_name": label.get("business_name"),
                "legacy_contact_route_expected": label.get("legacy_contact_route_expected"),
                "contact_route_expected": label.get("contact_route_expected"),
                "readiness_expected": label.get("readiness_expected"),
            })
        else:
            validate_label_schema(label, label_path=path)
            unchanged += 1
    return {
        "corpus": str(root),
        "changed_count": len(changed),
        "unchanged_count": unchanged,
        "changed": changed,
    }


def candidate_id_for(candidate: dict[str, Any]) -> str:
    candidate_id = str(candidate.get("candidate_id") or candidate.get("lead_id") or "").strip()
    if not candidate_id:
        raise ReplayCorpusError(f"candidate is missing candidate_id/lead_id: {candidate}")
    return candidate_id


def materialize_replay_state(
    *,
    corpus: dict[str, Any],
    state_root: str | Path,
) -> list[dict[str, Any]]:
    """Write replay candidates as lead JSON under an isolated state root."""
    root = Path(state_root)
    leads_dir = root / "leads"
    leads_dir.mkdir(parents=True, exist_ok=True)
    materialized: list[dict[str, Any]] = []
    corpus_root = Path(corpus["root"])

    for candidate in corpus["candidates"]:
        if isinstance(candidate.get("record"), dict):
            record = _resolve_project_root_tokens(dict(candidate["record"]))
        else:
            record = _materialize_collected_candidate(root=corpus_root, candidate=candidate, state_root=root)
        candidate_id = candidate_id_for(candidate)
        record.setdefault("lead_id", candidate_id)
        record.setdefault("production_sim_candidate_id", candidate_id)
        record.setdefault("production_sim_fixture", True)
        record.setdefault("generated_at", "2026-04-29T00:00:00+00:00")
        record.setdefault("status_history", [{"status": record.get("outreach_status") or "new", "timestamp": "2026-04-29T00:00:00+00:00"}])
        record = ensure_lead_dossier(record)
        persist_lead_record(record, state_root=root)
        materialized.append(record)

    return materialized


def _materialize_collected_candidate(*, root: Path, candidate: dict[str, Any], state_root: Path) -> dict[str, Any]:
    """Replay a collected live candidate through offline qualification.

    Collected corpora store captured HTML/search artifacts rather than fully
    persisted lead records. This adapter keeps replay network-free while still
    exercising the production qualification, contact, package, proof, and asset
    selection paths.
    """
    from .pitch import build_pitch
    from .preview import build_preview_html, build_preview_menu
    from .qualification import qualify_candidate
    from .record import create_lead_record, normalise_lead_contacts
    from .business_name import business_name_is_suspicious

    candidate_id = candidate_id_for(candidate)
    search_job = dict(candidate.get("source_search_job") or {})
    pages = _captured_pages_for_candidate(root=root, candidate=candidate)
    category = str(candidate.get("category_hint") or search_job.get("category") or "")
    qualification = qualify_candidate(
        business_name=str(candidate.get("business_name") or ""),
        website=str(candidate.get("website") or ""),
        category=category,
        pages=[{"url": page["url"], "html": page["html"]} for page in pages],
        rating=candidate.get("rating"),
        reviews=candidate.get("rating_count") or candidate.get("reviews"),
        address=str(candidate.get("address") or ""),
        phone=str(candidate.get("phone") or ""),
        place_id=str(candidate.get("place_id") or ""),
        map_url=str(candidate.get("map_url") or ""),
    )
    solution_check_reject = qualification.lead and _search_job_marks_existing_solution(search_job)
    suspicious_name_reject = qualification.lead and business_name_is_suspicious(qualification.business_name)
    contacts = _captured_contact_routes(candidate=candidate, pages=pages)

    if qualification.lead and not solution_check_reject and not suspicious_name_reject:
        preview_menu = build_preview_menu(
            assessment=qualification,
            snippets=qualification.evidence_snippets,
            business_name=qualification.business_name,
        )
        preview_html = build_preview_html(
            preview_menu=preview_menu,
            ticket_machine_hint=None,
            business_name=qualification.business_name,
        )
        pitch = build_pitch(
            business_name=qualification.business_name,
            category=qualification.primary_category_v1,
            preview_menu=preview_menu,
            ticket_machine_hint=None,
            recommended_package=qualification.recommended_primary_package,
        )
        record = create_lead_record(
            qualification=qualification,
            preview_html=preview_html,
            pitch_draft=pitch,
            contacts=contacts,
            source_query=str(search_job.get("query") or ""),
            source_search_job=search_job,
            matched_friction_evidence=_replay_matched_friction_evidence(qualification=qualification, search_job=search_job),
            state_root=state_root,
        )
    else:
        if solution_check_reject:
            rejection_reason = "already_solved_solution_check"
        elif suspicious_name_reject:
            rejection_reason = "invalid_business_name_detected"
        else:
            rejection_reason = qualification.rejection_reason
        english_state = "usable_complete" if solution_check_reject else qualification.english_menu_state
        record = {
            **qualification.to_dict(),
            "lead": False,
            "rejection_reason": rejection_reason,
            "english_availability": "clear_usable" if solution_check_reject else qualification.english_availability,
            "english_menu_state": english_state,
            "lead_id": candidate_id,
            "business_name": qualification.business_name or str(candidate.get("business_name") or ""),
            "website": qualification.website or str(candidate.get("website") or ""),
            "address": qualification.address or str(candidate.get("address") or ""),
            "phone": qualification.phone or str(candidate.get("phone") or ""),
            "place_id": qualification.place_id or str(candidate.get("place_id") or ""),
            "map_url": qualification.map_url or str(candidate.get("map_url") or ""),
            "rating": candidate.get("rating"),
            "reviews": candidate.get("rating_count") or candidate.get("reviews"),
            "category": category,
            "source_query": str(search_job.get("query") or ""),
            "source_search_job": search_job,
            "matched_friction_evidence": _replay_matched_friction_evidence(qualification=qualification, search_job=search_job),
            "source_urls": {
                "website": qualification.website or str(candidate.get("website") or ""),
                "map_url": qualification.map_url or str(candidate.get("map_url") or ""),
                "evidence_urls": qualification.evidence_urls,
            },
            "contacts": normalise_lead_contacts({
                "contacts": contacts,
                "website": str(candidate.get("website") or ""),
                "map_url": str(candidate.get("map_url") or ""),
                "generated_at": "2026-04-29T00:00:00+00:00",
            }),
            "pitch_draft": {},
            "outreach_assets_selected": [],
            "outreach_asset_template_family": "none",
            "outreach_status": "new",
        }

    record["production_sim_candidate_id"] = candidate_id
    record["production_sim_fixture"] = True
    record["production_sim_capture_status"] = str((candidate.get("capture") or {}).get("status") or "")
    record["production_sim_artifact_refs"] = _candidate_artifact_refs(candidate)
    return record


def _captured_pages_for_candidate(*, root: Path, candidate: dict[str, Any]) -> list[dict[str, str]]:
    pages: list[dict[str, str]] = []
    for page in (candidate.get("capture") or {}).get("pages") or []:
        rel_path = str(page.get("path") or "")
        path = root / rel_path
        if not rel_path or not path.exists():
            continue
        pages.append({
            "source": str(page.get("source") or "captured_page"),
            "url": str(page.get("url") or candidate.get("website") or ""),
            "path": rel_path,
            "html": path.read_text(encoding="utf-8", errors="ignore"),
        })
    return pages


def _captured_contact_routes(*, candidate: dict[str, Any], pages: list[dict[str, str]]) -> list[dict[str, Any]]:
    from .contact_crawler import extract_contact_signals
    from .record import normalise_lead_contacts

    website = str(candidate.get("website") or "").strip()
    phone = str(candidate.get("phone") or "").strip()
    address = str(candidate.get("address") or "").strip()
    map_url = str(candidate.get("map_url") or "").strip()
    generated_at = "2026-04-29T00:00:00+00:00"
    raw_contacts: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()

    def append(
        contact_type: str,
        value: str,
        *,
        label: str = "",
        href: str = "",
        source: str = "",
        source_url: str = "",
        confidence: str = "medium",
        actionable: bool = True,
        metadata: dict[str, Any] | None = None,
    ) -> None:
        cleaned = str(value or "").strip()
        if not cleaned:
            return
        key_value = re.sub(r"\D", "", cleaned) if contact_type == "phone" else cleaned.lower()
        key = (contact_type, key_value)
        if not key_value or key in seen:
            return
        seen.add(key)
        contact = {
            "type": contact_type,
            "value": cleaned,
            "label": label or cleaned,
            "href": href,
            "source": source,
            "source_url": source_url,
            "confidence": confidence,
            "discovered_at": generated_at,
            "status": "discovered" if actionable else "reference_only",
            "actionable": actionable,
        }
        for key, item in (metadata or {}).items():
            if item not in (None, "", []):
                contact[key] = item
        raw_contacts.append(contact)

    if website:
        append("website", website, label="Official website", href=website, source="homepage", source_url=website, confidence="high", actionable=False)
    if phone:
        append("phone", phone, href=f"tel:{re.sub(r'\D', '', phone)}", source="maps_listing", source_url=map_url or website, confidence="high", actionable=False)
    if address:
        append("walk_in", address, label="Walk-in route", source="maps_listing", source_url=map_url or website, confidence="high", actionable=False)
    if map_url:
        append("map_url", map_url, label="Map listing", href=map_url, source="maps_listing", source_url=map_url, confidence="high", actionable=False)

    for page in pages:
        if not _page_can_supply_business_contact(website=website, page=page):
            continue
        signals = extract_contact_signals(page["html"])
        source = str(page.get("source") or "captured_page")
        source_url = str(page.get("url") or "")
        for email in signals.emails:
            append("email", email, href=f"mailto:{email}", source=source, source_url=source_url, confidence="high")
        if signals.has_form:
            append(
                "contact_form",
                source_url,
                label="Contact form",
                href=source_url,
                source=source,
                source_url=source_url,
                metadata={
                    "form_actions": signals.form_actions,
                    "required_fields": signals.required_fields,
                },
            )
    return normalise_lead_contacts({
        "contacts": raw_contacts,
        "website": website,
        "map_url": map_url,
        "generated_at": generated_at,
    })


def _page_can_supply_business_contact(*, website: str, page: dict[str, str]) -> bool:
    source = str(page.get("source") or "")
    if source not in {"homepage", "contact_page"}:
        return False
    return bool(_host_key(website) and _host_key(website) == _host_key(str(page.get("url") or "")))


def _host_key(url: str) -> str:
    host = urllib.parse.urlparse(str(url or "")).netloc.lower()
    if host.startswith("www."):
        host = host[4:]
    return host


def _replay_matched_friction_evidence(*, qualification: Any, search_job: dict[str, Any]) -> list[str]:
    evidence = [str(item) for item in qualification.evidence_classes or [] if str(item)]
    expected = str(search_job.get("expected_friction") or "")
    purpose = str(search_job.get("purpose") or "")
    if expected:
        evidence.append(expected)
    if purpose:
        evidence.append(purpose)
    return sorted(set(evidence))


def _search_job_marks_existing_solution(search_job: dict[str, Any]) -> bool:
    job_id = str(search_job.get("job_id") or "")
    purpose = str(search_job.get("purpose") or "")
    expected = str(search_job.get("expected_friction") or "")
    haystack = " ".join([job_id, purpose, expected])
    return any(token in haystack for token in (
        "english_menu_check",
        "english_solution_check",
        "english_ticket_machine_check",
        "mobile_order_check",
        "mobile_order_solution_check",
        "multilingual_qr_check",
        "multilingual_solution_check",
        "ticket_machine_solution_check",
    ))


def _resolve_project_root_tokens(value: Any) -> Any:
    if isinstance(value, str):
        return value.replace("{PROJECT_ROOT}", str(PROJECT_ROOT))
    if isinstance(value, list):
        return [_resolve_project_root_tokens(item) for item in value]
    if isinstance(value, dict):
        return {key: _resolve_project_root_tokens(item) for key, item in value.items()}
    return value


def copy_corpus_snapshot(
    *,
    corpus_dir: str | Path,
    replay_root: str | Path,
) -> None:
    """Copy the deterministic fixture into the runtime replay artifact path."""
    source = Path(corpus_dir)
    target = Path(replay_root)
    if source.resolve() == target.resolve():
        write_json(target / "source.json", {"source_corpus": str(source), "snapshot": "source_equals_target"})
        return
    if target.exists():
        shutil.rmtree(target)
    shutil.copytree(source, target)
    write_json(target / "source.json", {"source_corpus": str(source)})


def prepare_stratified_labeling_workflow(
    *,
    corpus_dir: str | Path,
    sample_size: int = 120,
    seed: str = "production-sim-labeling-v1",
    output_dir: str | Path | None = None,
) -> dict[str, Any]:
    """Create draft labels and review queues for a collected replay corpus.

    This intentionally writes draft labels outside the manifest labels/ folder.
    Finalized labels must be copied into labels/ only after operator review.
    """
    root = Path(corpus_dir)
    corpus = load_replay_corpus(root, require_labels=False)
    candidates = list(corpus["candidates"])
    if not candidates:
        raise ReplayCorpusError(f"corpus has no candidates: {root}")
    if sample_size < 1:
        raise ReplayCorpusError("sample_size must be at least 1")

    workflow_dir = Path(output_dir) if output_dir else root / "labeling"
    drafts_dir = workflow_dir / "drafts"
    workflow_dir.mkdir(parents=True, exist_ok=True)
    drafts_dir.mkdir(parents=True, exist_ok=True)
    for stale in drafts_dir.glob("*.json"):
        stale.unlink()

    annotations = [_annotate_label_candidate(root, candidate) for candidate in candidates]
    selected = _select_stratified_annotations(annotations, sample_size=min(sample_size, len(annotations)), seed=seed)
    drafts: list[dict[str, Any]] = []
    for annotation in selected:
        draft = _draft_label_for_annotation(annotation)
        drafts.append(draft)
        write_json(drafts_dir / f"{draft['candidate_id']}.json", draft)

    sample_items = [_sample_item_for_annotation(annotation) for annotation in selected]
    review_queue = _label_review_queue(sample_items)
    coverage = _label_sample_coverage(sample_items)
    template = _label_template()
    checklist = _label_checklist(sample_size=len(sample_items))
    finalized_labels = len(corpus["labels"])

    sample_path = workflow_dir / "stratified-sample.json"
    queue_path = workflow_dir / "review-queue.json"
    template_path = workflow_dir / "label-template.json"
    checklist_path = workflow_dir / "operator-checklist.md"
    offline_plan_path = workflow_dir / "offline-replay-plan.json"
    dashboard_plan_path = workflow_dir / "dashboard-verification-plan.json"
    summary_path = workflow_dir / "summary.json"

    write_json(sample_path, sample_items)
    write_json(queue_path, review_queue)
    write_json(template_path, template)
    write_text(checklist_path, checklist)
    offline_plan = _offline_replay_plan(root=root, run_id=str(corpus["manifest"].get("run_id") or root.name), finalized_labels=finalized_labels)
    dashboard_plan = _dashboard_verification_plan(root=root, run_id=str(corpus["manifest"].get("run_id") or root.name), finalized_labels=finalized_labels)
    write_json(offline_plan_path, offline_plan)
    write_json(dashboard_plan_path, dashboard_plan)

    manifest = dict(corpus["manifest"])
    manifest.update({
        "label_count": finalized_labels,
        "labeling_workflow": {
            "sample_method": "stratified",
            "sample_size": len(sample_items),
            "sample_seed": seed,
            "workflow_dir": str(workflow_dir.relative_to(root) if workflow_dir.is_relative_to(root) else workflow_dir),
            "sample_file": str(sample_path.relative_to(root) if sample_path.is_relative_to(root) else sample_path),
            "drafts_dir": str(drafts_dir.relative_to(root) if drafts_dir.is_relative_to(root) else drafts_dir),
            "review_queue_file": str(queue_path.relative_to(root) if queue_path.is_relative_to(root) else queue_path),
            "template_file": str(template_path.relative_to(root) if template_path.is_relative_to(root) else template_path),
            "checklist_file": str(checklist_path.relative_to(root) if checklist_path.is_relative_to(root) else checklist_path),
            "offline_replay_plan_file": str(offline_plan_path.relative_to(root) if offline_plan_path.is_relative_to(root) else offline_plan_path),
            "dashboard_verification_plan_file": str(dashboard_plan_path.relative_to(root) if dashboard_plan_path.is_relative_to(root) else dashboard_plan_path),
            "finalized_label_count": finalized_labels,
            "offline_replay_ready": finalized_labels > 0,
            "dashboard_verification_ready": finalized_labels > 0,
            "expected_ready_policy": "ready_for_outreach labels must be high confidence or approved second-pass review",
        },
    })
    write_json(root / "manifest.json", manifest)

    summary = {
        "run_id": str(manifest.get("run_id") or root.name),
        "corpus": str(root),
        "sample_method": "stratified",
        "sample_size": len(sample_items),
        "candidate_count": len(candidates),
        "finalized_label_count": finalized_labels,
        "draft_label_count": len(drafts),
        "label_schema": "PRODUCTION_SIMULATION_TEST_PLAN.md",
        "sample_path": str(sample_path),
        "drafts_dir": str(drafts_dir),
        "review_queue_path": str(queue_path),
        "template_path": str(template_path),
        "checklist_path": str(checklist_path),
        "offline_replay_plan_path": str(offline_plan_path),
        "dashboard_verification_plan_path": str(dashboard_plan_path),
        "coverage": coverage,
        "review_queue_counts": {key: len(value) for key, value in review_queue.items()},
        "offline_replay_ready": finalized_labels > 0,
        "dashboard_verification_ready": finalized_labels > 0,
        "production_ready": False,
        "external_send_performed": False,
        "real_launch_batch_created": False,
        "next_required_fixes": [
            "Complete operator labels in labels/ with expected-ready labels high-confidence or approved by second pass.",
            "Run offline replay with --screenshots against the finalized labels.",
            "Verify dashboard screenshots and mocked-send payloads before any production-ready claim.",
        ],
    }
    write_json(summary_path, summary)
    summary["summary_path"] = str(summary_path)
    return summary


def collect_replay_corpus(
    *,
    run_id: str,
    replay_root: str | Path,
    city_set: str = "launch-markets",
    cities: list[str] | None = None,
    category: str = "all",
    limit_per_job: int = 5,
    stage: str = "pilot",
    serper_api_key: str = "",
    gl: str = "jp",
    fetch_timeout_seconds: int = 8,
    contact_pages_per_candidate: int = 2,
    evidence_pages_per_candidate: int = 2,
    maps_search_fn: Callable[..., Any] | None = None,
    web_search_fn: Callable[..., Any] | None = None,
    fetch_page_fn: Callable[..., str] | None = None,
    created_at: str | None = None,
) -> dict[str, Any]:
    """Collect a stratified search/fetch corpus without touching lead state.

    The collector only writes replay artifacts under state/search-replay. It
    does not qualify leads, create launch batches, or touch any send path.
    Tests pass mocked search/fetch callables; CLI use can pass real Serper
    credentials for a no-send pilot/broad capture.
    """
    if not run_id:
        raise ReplayCorpusError("run_id is required for collection artifacts")
    created_at = created_at or utc_now()
    category = normalise_search_category(category)
    selected_cities = cities or cities_for_market_set(city_set)
    if not selected_cities:
        raise ReplayCorpusError("at least one city is required for production-sim collect")
    if limit_per_job < 1:
        raise ReplayCorpusError("limit_per_job must be at least 1")

    using_default_maps = maps_search_fn is None
    maps_search = maps_search_fn or _default_maps_search
    web_search = web_search_fn or _default_web_search
    fetch_page = fetch_page_fn or _default_fetch_page
    if using_default_maps and not serper_api_key:
        raise ReplayCorpusError("production-sim collect requires --api-key/SERPER_API_KEY or an offline fixture")

    root = Path(replay_root) / run_id
    serper_dir = root / "serper"
    pages_dir = root / "pages"
    labels_dir = root / "labels"
    for directory in (serper_dir, pages_dir, labels_dir):
        directory.mkdir(parents=True, exist_ok=True)

    jobs = collection_search_jobs(category=category, cities=selected_cities)
    candidates: list[dict[str, Any]] = []
    candidates_by_id: dict[str, dict[str, Any]] = {}
    seen_keys: dict[str, str] = {}
    duplicates: list[dict[str, Any]] = []
    fetch_failures: list[dict[str, Any]] = []
    search_failures: list[dict[str, Any]] = []
    raw_candidate_count = 0

    for job_index, job in enumerate(jobs):
        artifact_rel = f"serper/{job_index:04d}-{slugify(job['city'])}-{slugify(job['job_id'])}-maps.json"
        try:
            raw_response = _call_maps_search(
                maps_search,
                query=job["query"],
                api_key=serper_api_key,
                gl=gl,
                timeout_seconds=fetch_timeout_seconds,
            )
        except Exception as exc:
            raw_response = {"places": [], "error": f"{type(exc).__name__}: {exc}"}
            search_failures.append({
                "job_id": job["job_id"],
                "query": job["query"],
                "city": job["city"],
                "category": job["category"],
                "artifact": artifact_rel,
                "error_type": type(exc).__name__,
                "error": str(exc),
            })
        raw_response = _normalise_maps_response(raw_response)
        write_json(root / artifact_rel, {
            "artifact_type": "serper_maps_response",
            "captured_at": created_at,
            "gl": gl,
            "job": job,
            "response": raw_response,
        })

        for rank, place in enumerate((raw_response.get("places") or [])[:limit_per_job], start=1):
            raw_candidate_count += 1
            source_ref = {
                "job_id": job["job_id"],
                "query": job["query"],
                "city": job["city"],
                "category": job["category"],
                "rank": rank,
                "serper_artifact": artifact_rel,
            }
            keys = _dedupe_keys_for_place(place)
            duplicate_of = next((seen_keys[key] for key in keys if key in seen_keys), "")
            if duplicate_of:
                duplicate_record = {
                    "duplicate_of": duplicate_of,
                    "source_job": source_ref,
                    "matched_keys": [key for key in keys if key in seen_keys],
                    "business_name": _place_name(place),
                    "website": str(place.get("website") or ""),
                    "address": str(place.get("address") or ""),
                    "phone": str(place.get("phoneNumber") or place.get("phone") or ""),
                    "place_id": str(place.get("placeId") or ""),
                }
                duplicates.append(duplicate_record)
                if duplicate_of in candidates_by_id:
                    candidates_by_id[duplicate_of].setdefault("duplicate_source_jobs", []).append(source_ref)
                continue

            candidate_id = _candidate_id_for_place(place)
            for key in keys:
                seen_keys[key] = candidate_id
            candidate = {
                "candidate_id": candidate_id,
                "business_name": _place_name(place),
                "website": str(place.get("website") or ""),
                "address": str(place.get("address") or ""),
                "phone": str(place.get("phoneNumber") or place.get("phone") or ""),
                "place_id": str(place.get("placeId") or ""),
                "map_url": str(place.get("link") or place.get("mapUrl") or ""),
                "rating": place.get("rating"),
                "rating_count": place.get("ratingCount") or place.get("reviews"),
                "category_hint": job["category"],
                "source_search_job": job,
                "source_jobs": [source_ref],
                "duplicate_source_jobs": [],
                "dedupe_keys": keys,
                "capture": {
                    "status": "pending",
                    "serper_maps_artifacts": [artifact_rel],
                    "serper_web_artifacts": [],
                    "pages": [],
                    "fetch_failures": [],
                },
            }
            candidates.append(candidate)
            candidates_by_id[candidate_id] = candidate

    for candidate in candidates:
        _capture_candidate_pages(
            root=root,
            pages_dir=pages_dir,
            serper_dir=serper_dir,
            candidate=candidate,
            web_search_fn=web_search,
            fetch_page_fn=fetch_page,
            serper_api_key=serper_api_key,
            gl=gl,
            fetch_timeout_seconds=fetch_timeout_seconds,
            contact_pages_per_candidate=contact_pages_per_candidate,
            evidence_pages_per_candidate=evidence_pages_per_candidate,
            created_at=created_at,
            fetch_failures=fetch_failures,
        )

    write_json(root / "candidates.json", candidates)
    write_json(root / "duplicates.json", duplicates)
    write_json(root / "fetch-failures.json", fetch_failures)
    write_json(root / "search-failures.json", search_failures)

    fetch_success_count = sum(len((candidate.get("capture") or {}).get("pages") or []) for candidate in candidates)
    manifest = {
        "schema_version": COLLECTION_SCHEMA_VERSION,
        "run_id": run_id,
        "run_scope": "pilot_broad_collection_scaffold",
        "created_for": "PRODUCTION_SIMULATION_TEST_PLAN.md",
        "created_at": created_at,
        "stage": stage,
        "city_set": city_set,
        "cities": selected_cities,
        "category": category,
        "limit_per_job": limit_per_job,
        "gl": gl,
        "network": "mocked_offline_fixture" if not using_default_maps else "live_serper_and_fetch_capture",
        "external_send_allowed": False,
        "launch_batch_allowed": False,
        "offline_replay_compatible": True,
        "requires_labels_before_replay": True,
        "candidates_file": "candidates.json",
        "labels_dir": "labels",
        "serper_dir": "serper",
        "pages_dir": "pages",
        "duplicates_file": "duplicates.json",
        "fetch_failures_file": "fetch-failures.json",
        "search_failures_file": "search-failures.json",
        "search_job_count": len(jobs),
        "search_jobs": jobs,
        "raw_candidate_count": raw_candidate_count,
        "candidate_count": len(candidates),
        "duplicate_count": len(duplicates),
        "label_count": 0,
        "fetch_success_count": fetch_success_count,
        "fetch_failure_count": len(fetch_failures),
        "search_failure_count": len(search_failures),
        "strata": _collection_strata(jobs),
    }
    write_json(root / "manifest.json", manifest)
    return {
        "run_id": run_id,
        "root": str(root),
        "manifest_path": str(root / "manifest.json"),
        "manifest": manifest,
        "candidates": candidates,
        "duplicates": duplicates,
        "fetch_failures": fetch_failures,
        "search_failures": search_failures,
        "external_send_performed": False,
        "real_launch_batch_created": False,
    }


def _annotate_label_candidate(root: Path, candidate: dict[str, Any]) -> dict[str, Any]:
    search_job = dict(candidate.get("source_search_job") or {})
    text = _candidate_label_text(root, candidate)
    evidence_profile = _evidence_profile(candidate, text)
    contact_route = _contact_route_profile(candidate, text)
    suspected_class = _suspected_label_class(candidate, evidence_profile=evidence_profile, contact_route=contact_route, text=text)
    return {
        "candidate": candidate,
        "candidate_id": candidate_id_for(candidate),
        "market": str(search_job.get("city") or ""),
        "category": str(candidate.get("category_hint") or search_job.get("category") or ""),
        "search_job": str(search_job.get("job_id") or ""),
        "suspected_class": suspected_class,
        "evidence_profile": evidence_profile,
        "contact_route_profile": contact_route,
        "capture_status": str((candidate.get("capture") or {}).get("status") or ""),
        "artifact_refs": _candidate_artifact_refs(candidate),
    }


def _select_stratified_annotations(
    annotations: list[dict[str, Any]],
    *,
    sample_size: int,
    seed: str,
) -> list[dict[str, Any]]:
    selected: dict[str, dict[str, Any]] = {}
    dimensions = (
        ("market_category", lambda item: f"{item['market']}:{item['category']}"),
        ("search_job", lambda item: item["search_job"]),
        ("suspected_class", lambda item: item["suspected_class"]),
        ("evidence_profile", lambda item: item["evidence_profile"]),
        ("contact_route_profile", lambda item: item["contact_route_profile"]),
    )

    for _, getter in dimensions:
        groups: dict[str, list[dict[str, Any]]] = defaultdict(list)
        for annotation in annotations:
            groups[str(getter(annotation) or "unknown")].append(annotation)
        for key in sorted(groups):
            if len(selected) >= sample_size:
                break
            pick = _first_unselected(groups[key], selected, seed)
            if pick:
                selected[pick["candidate_id"]] = pick
        if len(selected) >= sample_size:
            break

    counts: dict[str, Counter[str]] = {name: Counter() for name, _ in dimensions}
    for item in selected.values():
        for name, getter in dimensions:
            counts[name][str(getter(item) or "unknown")] += 1

    while len(selected) < sample_size:
        remaining = [item for item in annotations if item["candidate_id"] not in selected]
        if not remaining:
            break
        remaining.sort(
            key=lambda item: (
                -_diversity_score(item, dimensions=dimensions, counts=counts),
                _stable_hash(f"{seed}:{item['candidate_id']}"),
            )
        )
        pick = remaining[0]
        selected[pick["candidate_id"]] = pick
        for name, getter in dimensions:
            counts[name][str(getter(pick) or "unknown")] += 1

    return sorted(selected.values(), key=lambda item: (_stable_hash(f"{seed}:{item['candidate_id']}"), item["candidate_id"]))


def _first_unselected(items: list[dict[str, Any]], selected: dict[str, dict[str, Any]], seed: str) -> dict[str, Any] | None:
    for item in sorted(items, key=lambda value: (_stable_hash(f"{seed}:{value['candidate_id']}"), value["candidate_id"])):
        if item["candidate_id"] not in selected:
            return item
    return None


def _diversity_score(
    item: dict[str, Any],
    *,
    dimensions: tuple[tuple[str, Callable[[dict[str, Any]], str]], ...],
    counts: dict[str, Counter[str]],
) -> float:
    score = 0.0
    for name, getter in dimensions:
        value = str(getter(item) or "unknown")
        score += 1.0 / (1 + counts[name][value])
    return score


def _sample_item_for_annotation(annotation: dict[str, Any]) -> dict[str, Any]:
    candidate = annotation["candidate"]
    search_job = dict(candidate.get("source_search_job") or {})
    return {
        "candidate_id": annotation["candidate_id"],
        "business_name": candidate.get("business_name"),
        "website": candidate.get("website"),
        "address": candidate.get("address"),
        "phone": candidate.get("phone"),
        "category_hint": candidate.get("category_hint"),
        "source_search_job": search_job,
        "sample_strata": {
            "market": annotation["market"],
            "category": annotation["category"],
            "search_job": annotation["search_job"],
            "suspected_class": annotation["suspected_class"],
            "evidence_profile": annotation["evidence_profile"],
            "contact_route_profile": annotation["contact_route_profile"],
            "capture_status": annotation["capture_status"],
        },
        "artifact_refs": annotation["artifact_refs"],
        "draft_label_path": f"labeling/drafts/{annotation['candidate_id']}.json",
        "operator_action": "inspect artifacts, finalize label JSON under labels/, then run production-sim replay",
    }


def _draft_label_for_annotation(annotation: dict[str, Any]) -> dict[str, Any]:
    candidate = annotation["candidate"]
    contact_expected = annotation["contact_route_profile"]
    if contact_expected not in LABEL_CONTACT_ROUTE_VALUES:
        contact_expected = "none"
    package_expected = _draft_package_expected(annotation)
    readiness_expected = "manual_review"
    rejection_reason = "needs_operator_label"
    if annotation["suspected_class"].startswith("suspected_disqualified"):
        readiness_expected = "disqualified"
        rejection_reason = annotation["suspected_class"].replace("suspected_disqualified_", "")

    return {
        "label_status": "draft_needs_operator_review",
        "candidate_id": annotation["candidate_id"],
        "business_name": candidate.get("business_name") or "",
        "website": candidate.get("website") or "",
        "address": candidate.get("address") or "",
        "category_expected": annotation["category"] if annotation["category"] in {"ramen", "izakaya"} else "out_of_scope",
        "readiness_expected": readiness_expected,
        "rejection_reason_expected": rejection_reason,
        "package_expected": package_expected,
        "contact_route_expected": contact_expected,
        "inline_assets_expected": _draft_inline_assets(annotation, contact_expected=contact_expected),
        "ticket_machine_state_expected": _draft_ticket_machine_state(annotation),
        "english_menu_state_expected": _draft_english_menu_state(annotation),
        "proof_strength_minimum": "gold" if annotation["capture_status"] == "captured" else "operator_only",
        "label_confidence": "low",
        "label_notes": "Draft placeholder. Do not move to labels/ until operator evidence review is complete.",
        "second_pass_review": {
            "required": annotation["suspected_class"] == "suspected_ready_review_required",
            "status": "pending" if annotation["suspected_class"] == "suspected_ready_review_required" else "not_required",
            "reason": "expected-ready candidates require high-confidence label or approved second-pass review",
        },
        "sample_strata": {
            "market": annotation["market"],
            "category": annotation["category"],
            "search_job": annotation["search_job"],
            "suspected_class": annotation["suspected_class"],
            "evidence_profile": annotation["evidence_profile"],
            "contact_route_profile": annotation["contact_route_profile"],
            "capture_status": annotation["capture_status"],
        },
        "artifact_refs": annotation["artifact_refs"],
    }


def _label_review_queue(sample_items: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    expected_ready = [
        _queue_item(item, reason="suspected ready; requires high-confidence final label or approved second pass")
        for item in sample_items
        if item["sample_strata"]["suspected_class"] == "suspected_ready_review_required"
    ]
    low_confidence = [
        _queue_item(item, reason="draft label starts low confidence until operator completes evidence review")
        for item in sample_items
    ]
    return {
        "expected_ready_second_pass_required": expected_ready,
        "low_confidence_drafts": low_confidence,
        "pipeline_disagreement_after_replay": [],
    }


def _queue_item(item: dict[str, Any], *, reason: str) -> dict[str, Any]:
    return {
        "candidate_id": item["candidate_id"],
        "business_name": item.get("business_name") or "",
        "market": item["sample_strata"]["market"],
        "category": item["sample_strata"]["category"],
        "search_job": item["sample_strata"]["search_job"],
        "draft_label_path": item["draft_label_path"],
        "reason": reason,
    }


def _label_sample_coverage(sample_items: list[dict[str, Any]]) -> dict[str, dict[str, int]]:
    dimensions = ("market", "category", "search_job", "suspected_class", "evidence_profile", "contact_route_profile", "capture_status")
    coverage: dict[str, dict[str, int]] = {}
    for dimension in dimensions:
        counter = Counter(str(item["sample_strata"].get(dimension) or "unknown") for item in sample_items)
        coverage[dimension] = dict(sorted(counter.items()))
    return coverage


def _label_template() -> dict[str, Any]:
    return {
        "candidate_id": "",
        "business_name": "",
        "website": "",
        "address": "",
        "category_expected": "ramen|izakaya|out_of_scope",
        "readiness_expected": "ready_for_outreach|manual_review|disqualified",
        "rejection_reason_expected": "",
        "package_expected": "package_1_remote_30k|package_2_printed_delivered_45k|package_3_qr_menu_65k|custom_quote|none",
        "contact_route_expected": "email|contact_form|none",
        "inline_assets_expected": ["ramen_food_menu", "ticket_machine_guide"],
        "ticket_machine_state_expected": "present|absent|unknown|already_english_supported",
        "english_menu_state_expected": "missing|weak_partial|image_only|usable_complete|unknown",
        "proof_strength_minimum": "gold|operator_only|none",
        "label_confidence": "high|medium|low",
        "label_notes": "",
        "second_pass_review": {
            "required": False,
            "status": "not_required|pending|approved",
            "reviewer": "",
            "notes": "",
        },
    }


def _label_checklist(*, sample_size: int) -> str:
    return "\n".join([
        "# Production Simulation Labeling Checklist",
        "",
        f"Sample size: {sample_size}",
        "",
        "Final labels must use the schema in PRODUCTION_SIMULATION_TEST_PLAN.md.",
        "Draft files under labeling/drafts/ are not replay labels. Copy reviewed labels into labels/ only after completing this checklist.",
        "",
        "For every candidate:",
        "",
        "1. Inspect the Maps/search artifact, captured pages, fetch failures, and source search job.",
        "2. Confirm Japan-only physical location and ramen/izakaya scope.",
        "3. Mark chains, branches, wrong categories, already-English, QR/mobile-order solved, thin-menu, unsafe-proof, and bad-contact cases.",
        "4. Set expected readiness, package, contact route, inline assets, ticket-machine state, English-menu state, and proof minimum.",
        "5. Keep label_confidence low or medium unless the evidence is strong enough to drive a hard oracle result.",
        "6. Any ready_for_outreach label must be label_confidence=high or have second_pass_review.status=approved.",
        "7. Expected-ready labels need a second reviewer whenever confidence is not already high.",
        "8. Do not run real outreach, create a launch batch, or mutate live lead state during labeling.",
        "",
        "After finalized labels exist:",
        "",
        "1. Run production-sim replay against this corpus with --screenshots.",
        "2. Review decisions.json, report.json, mock-email-payloads.json, and screenshot-manifest.json.",
        "3. Fix every P0/P1 finding before any production-ready claim.",
        "",
    ])


def _offline_replay_plan(*, root: Path, run_id: str, finalized_labels: int) -> dict[str, Any]:
    replay_ready = finalized_labels > 0
    return {
        "run_id": run_id,
        "corpus": str(root),
        "ready": replay_ready,
        "blocked_by": [] if replay_ready else ["finalized_label_count=0"],
        "required_before_run": [
            "Move reviewed label JSON files into labels/.",
            "Expected-ready labels must be high confidence or approved by second-pass review.",
            "Keep labels under the schema from PRODUCTION_SIMULATION_TEST_PLAN.md.",
        ],
        "command_after_labels": (
            f".venv/bin/python -m pipeline.cli production-sim replay "
            f"--corpus {root} --run-id {run_id} --screenshots --fail-on p0,p1"
        ),
        "expected_outputs": [
            f"state/production-sim/{run_id}/report.json",
            f"state/production-sim/{run_id}/decisions.json",
            f"state/production-sim/{run_id}/mock-email-payloads.json",
            f"state/production-sim/{run_id}/screenshot-manifest.json",
        ],
        "send_policy": {
            "external_send_allowed": False,
            "real_launch_batch_allowed": False,
            "live_lead_state_mutation_allowed": False,
        },
    }


def _dashboard_verification_plan(*, root: Path, run_id: str, finalized_labels: int) -> dict[str, Any]:
    dashboard_ready = finalized_labels > 0
    return {
        "run_id": run_id,
        "corpus": str(root),
        "ready": dashboard_ready,
        "blocked_by": [] if dashboard_ready else ["finalized_label_count=0"],
        "screenshot_dir": f"state/qa-screenshots/{run_id}",
        "required_screenshot_states": [
            "dashboard_overview",
            "ready_lead_card",
            "manual_review_card",
            "disqualified_card",
            "lead_dossier",
            "proof_section",
            "package_recommendation_section",
            "contact_route_section",
            "outreach_editor",
            "inline_menu_sample",
            "inline_ticket_machine_sample",
            "inline_izakaya_sample",
            "mocked_send_confirmation",
            "blocked_send_error",
        ],
        "operator_assertions": [
            "readiness and rejection reasons are visible",
            "proof strength and evidence score are visible",
            "package fit and selected contact route are visible",
            "inline samples match the expected profile",
            "non-ready records cannot send",
        ],
        "send_policy": {
            "external_send_allowed": False,
            "real_launch_batch_allowed": False,
            "live_lead_state_mutation_allowed": False,
        },
    }


def _candidate_label_text(root: Path, candidate: dict[str, Any], *, max_chars: int = 16000) -> str:
    parts = [
        str(candidate.get("business_name") or ""),
        str(candidate.get("website") or ""),
        str(candidate.get("address") or ""),
        str(candidate.get("phone") or ""),
        json.dumps(candidate.get("source_search_job") or {}, ensure_ascii=False),
    ]
    for page in (candidate.get("capture") or {}).get("pages") or []:
        rel = str(page.get("path") or "")
        path = root / rel
        if path.exists():
            raw = path.read_text(encoding="utf-8", errors="ignore")[:max_chars]
            parts.append(_html_to_label_text(raw))
    return " ".join(parts).lower()


def _html_to_label_text(html: str) -> str:
    text = re.sub(r"<(script|style)\b.*?</\1>", " ", html, flags=re.I | re.S)
    text = re.sub(r"<[^>]+>", " ", text)
    return re.sub(r"\s+", " ", text)


def _evidence_profile(candidate: dict[str, Any], text: str) -> str:
    job_id = str((candidate.get("source_search_job") or {}).get("job_id") or "")
    purpose = str((candidate.get("source_search_job") or {}).get("purpose") or "")
    if "chain" in job_id or "chain" in purpose:
        return "chain_branch_check"
    if "multilingual" in job_id:
        return "multilingual_qr_check"
    if "mobile_order" in job_id:
        return "mobile_order_check"
    if "english_ticket" in job_id:
        return "english_ticket_machine_check"
    if "english_menu" in job_id:
        return "english_menu_check"
    if "ticket_machine" in job_id or "ticket machine" in text or "券売機" in text:
        return "ramen_ticket_machine"
    if "meal_ticket" in job_id or "食券" in text:
        return "ramen_meal_ticket"
    if "nomihodai" in job_id or "course" in job_id or "飲み放題" in text or "コース" in text:
        return "izakaya_course_nomihodai"
    if "oshinagaki" in job_id or "お品書き" in text:
        return "izakaya_oshinagaki"
    if "social" in job_id or "instagram" in text:
        return "social_menu"
    if "official_menu" in job_id:
        return "official_menu"
    if "menu_photo" in job_id or "メニュー" in text or "menu" in text:
        return "menu_photo_or_page"
    return "unknown"


def _contact_route_profile(candidate: dict[str, Any], text: str) -> str:
    website = str(candidate.get("website") or "").lower()
    if re.search(r"mailto:|[\w.+-]+@[\w.-]+\.[a-z]{2,}", text):
        return "email"
    if re.search(r"\bcontact\s+form\b|\binquiry\b|/contact\b|お問い合わせ", text):
        return "contact_form"
    if website:
        return "website_only"
    return "none"


def _suspected_label_class(candidate: dict[str, Any], *, evidence_profile: str, contact_route: str, text: str) -> str:
    name = str(candidate.get("business_name") or "").lower()
    status = str((candidate.get("capture") or {}).get("status") or "")
    if evidence_profile == "chain_branch_check" or any(token in name for token in ("ichiran", "ippudo", "afuri", "torikizoku")):
        return "suspected_disqualified_chain"
    if evidence_profile in {"english_menu_check", "english_ticket_machine_check", "multilingual_qr_check", "mobile_order_check"}:
        return "suspected_disqualified_already_solved"
    if "united states" in text or "new york" in text:
        return "suspected_disqualified_non_japan"
    if status == "fetch_failed":
        return "suspected_manual_fetch_failed"
    if contact_route in {"none", "website_only"}:
        return "suspected_manual_no_supported_contact"
    if evidence_profile in {
        "ramen_ticket_machine",
        "ramen_meal_ticket",
        "izakaya_course_nomihodai",
        "izakaya_oshinagaki",
        "official_menu",
        "menu_photo_or_page",
    } and status == "captured":
        return "suspected_ready_review_required"
    return "suspected_manual_review"


def _draft_package_expected(annotation: dict[str, Any]) -> str:
    category = annotation["category"]
    evidence_profile = annotation["evidence_profile"]
    suspected = annotation["suspected_class"]
    if suspected.startswith("suspected_disqualified"):
        return "none"
    if category == "ramen" and evidence_profile in {"ramen_ticket_machine", "ramen_meal_ticket"}:
        return "package_2_printed_delivered_45k"
    if category == "ramen":
        return "package_1_remote_30k"
    if category == "izakaya" and evidence_profile == "izakaya_course_nomihodai":
        return "package_3_qr_menu_65k"
    if category == "izakaya":
        return "package_2_printed_delivered_45k"
    return "none"


def _draft_inline_assets(annotation: dict[str, Any], *, contact_expected: str) -> list[str]:
    if contact_expected == "contact_form":
        return []
    if annotation["category"] == "ramen":
        assets = ["ramen_food_menu"]
        if annotation["evidence_profile"] in {"ramen_ticket_machine", "ramen_meal_ticket", "english_ticket_machine_check"}:
            assets.append("ticket_machine_guide")
        return assets
    if annotation["category"] == "izakaya":
        return ["izakaya_food_drinks"]
    return []


def _draft_ticket_machine_state(annotation: dict[str, Any]) -> str:
    if annotation["evidence_profile"] in {"ramen_ticket_machine", "ramen_meal_ticket"}:
        return "present"
    if annotation["evidence_profile"] == "english_ticket_machine_check":
        return "already_english_supported"
    if annotation["category"] == "izakaya":
        return "absent"
    return "unknown"


def _draft_english_menu_state(annotation: dict[str, Any]) -> str:
    if annotation["evidence_profile"] in {"english_menu_check", "multilingual_qr_check", "mobile_order_check", "english_ticket_machine_check"}:
        return "usable_complete"
    return "unknown"


def _candidate_artifact_refs(candidate: dict[str, Any]) -> dict[str, Any]:
    capture = candidate.get("capture") or {}
    return {
        "serper_maps_artifacts": list(capture.get("serper_maps_artifacts") or []),
        "serper_web_artifacts": list(capture.get("serper_web_artifacts") or []),
        "pages": list(capture.get("pages") or []),
        "fetch_failures": list(capture.get("fetch_failures") or []),
    }


def _stable_hash(value: str) -> str:
    return hashlib.sha1(value.encode("utf-8")).hexdigest()


def cities_for_market_set(city_set: str) -> list[str]:
    value = str(city_set or "launch-markets").strip().lower()
    if value in {"launch-markets", "launch_markets", "pilot", "broad"}:
        return list(DEFAULT_LAUNCH_MARKETS)
    if value in {"mini", "test"}:
        return ["Shibuya", "Namba", "Gion"]
    raise ReplayCorpusError(f"unknown city set: {city_set}")


def collection_search_jobs(*, category: str, cities: list[str]) -> list[dict[str, str]]:
    jobs: list[dict[str, str]] = []
    for city in cities:
        for job in search_jobs_for_scope(category=category, city=city):
            enriched = dict(job)
            enriched["city"] = city
            enriched["stratum"] = f"{city}:{enriched['category']}:{enriched['job_id']}"
            jobs.append(enriched)
        jobs.extend(_explicit_evidence_check_jobs(category=category, city=city))
    return jobs


def fixture_collect_adapters(fixture_path: str | Path) -> tuple[Callable[..., Any], Callable[..., Any], Callable[..., str]]:
    fixture = read_json(Path(fixture_path))
    if not isinstance(fixture, dict):
        raise ReplayCorpusError(f"invalid collection fixture: {fixture_path}")
    maps = fixture.get("maps") or {}
    web = fixture.get("web") or {}
    pages = fixture.get("pages") or {}
    failures = fixture.get("failures") or {}

    def maps_search(*, query: str, **_: Any) -> Any:
        return maps.get(query) or {"places": []}

    def web_search(*, query: str, **_: Any) -> Any:
        return web.get(query) or {"organic": []}

    def fetch_page(url: str, **_: Any) -> str:
        if url in failures:
            raise RuntimeError(str(failures[url]))
        if url not in pages:
            raise RuntimeError(f"fixture missing page: {url}")
        return str(pages[url])

    return maps_search, web_search, fetch_page


def _explicit_evidence_check_jobs(*, category: str, city: str) -> list[dict[str, str]]:
    categories = ["ramen", "izakaya"] if normalise_search_category(category) == "all" else [normalise_search_category(category)]
    jobs: list[dict[str, str]] = []
    for value in categories:
        if value == "ramen":
            checks = [
                ("english_menu_check", f"英語メニュー ラーメン {city}", "english_solution_check", "english_menu_check"),
                ("multilingual_qr_check", f"多言語 QR ラーメン {city}", "multilingual_solution_check", "multilingual_qr_check"),
                ("mobile_order_check", f"モバイルオーダー ラーメン {city}", "mobile_order_solution_check", "mobile_order_check"),
                ("english_ticket_machine_check", f"英語 券売機 ラーメン {city}", "ticket_machine_solution_check", "english_ticket_machine_check"),
                ("chain_branch_check", f"ラーメン {city} チェーン 店舗一覧", "chain_infrastructure_check", "chain_branch_check"),
            ]
        else:
            checks = [
                ("english_menu_check", f"英語メニュー 居酒屋 {city}", "english_solution_check", "english_menu_check"),
                ("multilingual_qr_check", f"多言語 QR 居酒屋 {city}", "multilingual_solution_check", "multilingual_qr_check"),
                ("mobile_order_check", f"モバイルオーダー 居酒屋 {city}", "mobile_order_solution_check", "mobile_order_check"),
                ("chain_branch_check", f"居酒屋 {city} チェーン 店舗一覧", "chain_infrastructure_check", "chain_branch_check"),
            ]
        for suffix, query, purpose, expected in checks:
            jobs.append({
                "job_id": f"{value}_{suffix}",
                "query": query,
                "category": value,
                "purpose": purpose,
                "expected_friction": expected,
                "city": city,
                "stratum": f"{city}:{value}:{value}_{suffix}",
            })
    return jobs


def _capture_candidate_pages(
    *,
    root: Path,
    pages_dir: Path,
    serper_dir: Path,
    candidate: dict[str, Any],
    web_search_fn: Callable[..., Any],
    fetch_page_fn: Callable[..., str],
    serper_api_key: str,
    gl: str,
    fetch_timeout_seconds: int,
    contact_pages_per_candidate: int,
    evidence_pages_per_candidate: int,
    created_at: str,
    fetch_failures: list[dict[str, Any]],
) -> None:
    website = str(candidate.get("website") or "").strip()
    candidate_id = str(candidate["candidate_id"])
    html = ""
    if website:
        html = _capture_page(
            root=root,
            pages_dir=pages_dir,
            candidate=candidate,
            url=website,
            source="homepage",
            fetch_page_fn=fetch_page_fn,
            timeout_seconds=fetch_timeout_seconds,
            created_at=created_at,
            fetch_failures=fetch_failures,
        )
    else:
        _record_fetch_failure(
            candidate=candidate,
            url="",
            source="homepage",
            error_type="MissingWebsite",
            error="candidate has no website URL",
            fetch_failures=fetch_failures,
        )

    if html:
        for url in _contact_urls(website, html, limit=contact_pages_per_candidate):
            _capture_page(
                root=root,
                pages_dir=pages_dir,
                candidate=candidate,
                url=url,
                source="contact_page",
                fetch_page_fn=fetch_page_fn,
                timeout_seconds=fetch_timeout_seconds,
                created_at=created_at,
                fetch_failures=fetch_failures,
            )

    evidence_urls_seen = {
        str(page.get("url") or "")
        for page in (candidate.get("capture") or {}).get("pages") or []
    }
    evidence_pages_captured = 0
    search_job = dict(candidate.get("source_search_job") or {})
    for index, query in enumerate(_targeted_queries(candidate), start=1):
        artifact_rel = f"serper/{candidate_id}-evidence-{index:02d}.json"
        try:
            raw_response = _call_web_search(
                web_search_fn,
                query=query,
                api_key=serper_api_key,
                gl=gl,
                timeout_seconds=fetch_timeout_seconds,
            )
        except Exception as exc:
            raw_response = {"organic": [], "error": f"{type(exc).__name__}: {exc}"}
        raw_response = _normalise_web_response(raw_response)
        write_json(serper_dir / Path(artifact_rel).name, {
            "artifact_type": "serper_organic_response",
            "captured_at": created_at,
            "gl": gl,
            "candidate_id": candidate_id,
            "business_name": candidate.get("business_name"),
            "query": query,
            "source_search_job": search_job,
            "response": raw_response,
        })
        candidate["capture"].setdefault("serper_web_artifacts", []).append(artifact_rel)
        for result in raw_response.get("organic") or []:
            link = str(result.get("link") or "").strip()
            if not link or link in evidence_urls_seen or _blocked_capture_link(link):
                continue
            evidence_urls_seen.add(link)
            captured_html = _capture_page(
                root=root,
                pages_dir=pages_dir,
                candidate=candidate,
                url=link,
                source="targeted_evidence_page",
                fetch_page_fn=fetch_page_fn,
                timeout_seconds=fetch_timeout_seconds,
                created_at=created_at,
                fetch_failures=fetch_failures,
            )
            if captured_html:
                evidence_pages_captured += 1
            if evidence_pages_captured >= evidence_pages_per_candidate:
                break
        if evidence_pages_captured >= evidence_pages_per_candidate:
            break

    pages = (candidate.get("capture") or {}).get("pages") or []
    failures = (candidate.get("capture") or {}).get("fetch_failures") or []
    if pages:
        candidate["capture"]["status"] = "captured"
    elif failures:
        candidate["capture"]["status"] = "fetch_failed"
    else:
        candidate["capture"]["status"] = "no_fetch_attempted"


def _capture_page(
    *,
    root: Path,
    pages_dir: Path,
    candidate: dict[str, Any],
    url: str,
    source: str,
    fetch_page_fn: Callable[..., str],
    timeout_seconds: int,
    created_at: str,
    fetch_failures: list[dict[str, Any]],
) -> str:
    candidate_id = str(candidate["candidate_id"])
    try:
        html = _call_fetch(fetch_page_fn, url=url, timeout_seconds=timeout_seconds)
    except Exception as exc:
        _record_fetch_failure(
            candidate=candidate,
            url=url,
            source=source,
            error_type=type(exc).__name__,
            error=str(exc),
            fetch_failures=fetch_failures,
        )
        return ""
    digest = hashlib.sha1(f"{source}|{url}".encode("utf-8")).hexdigest()[:10]
    page_rel = f"pages/{candidate_id}/{source}-{digest}.html"
    write_text(pages_dir / candidate_id / f"{source}-{digest}.html", html)
    candidate["capture"].setdefault("pages", []).append({
        "source": source,
        "url": url,
        "path": page_rel,
        "captured_at": created_at,
        "bytes": len(html.encode("utf-8")),
        "sha256": sha256_text(html),
    })
    return html


def _record_fetch_failure(
    *,
    candidate: dict[str, Any],
    url: str,
    source: str,
    error_type: str,
    error: str,
    fetch_failures: list[dict[str, Any]],
) -> None:
    item = {
        "candidate_id": str(candidate.get("candidate_id") or ""),
        "business_name": str(candidate.get("business_name") or ""),
        "url": url,
        "source": source,
        "error_type": error_type,
        "error": error,
    }
    candidate.setdefault("capture", {}).setdefault("fetch_failures", []).append(item)
    fetch_failures.append(item)


def _targeted_queries(candidate: dict[str, Any]) -> list[str]:
    from .search import _targeted_evidence_queries

    return _targeted_evidence_queries(
        business_name=str(candidate.get("business_name") or ""),
        category=str(candidate.get("category_hint") or ""),
        search_job=dict(candidate.get("source_search_job") or {}),
    )


def _contact_urls(website: str, html: str, *, limit: int) -> list[str]:
    from .search import _contact_candidate_urls

    return _contact_candidate_urls(website, html, limit=limit)


def _default_maps_search(**kwargs: Any) -> dict[str, Any]:
    payload = json.dumps({"q": kwargs["query"], "gl": kwargs.get("gl") or "jp"}).encode("utf-8")
    request = urllib.request.Request("https://google.serper.dev/maps", data=payload, headers={
        "Content-Type": "application/json",
        "X-API-KEY": str(kwargs.get("api_key") or ""),
    })
    with urllib.request.urlopen(request, timeout=int(kwargs.get("timeout_seconds") or 8)) as response:
        return json.loads(response.read().decode("utf-8"))


def _default_web_search(**kwargs: Any) -> dict[str, Any]:
    from .search import run_web_search

    return run_web_search(**kwargs)


def _default_fetch_page(url: str, **kwargs: Any) -> str:
    from .search import _fetch_page

    return _fetch_page(url, timeout_seconds=int(kwargs.get("timeout_seconds") or 8))


def _call_maps_search(func: Callable[..., Any], **kwargs: Any) -> Any:
    try:
        return func(**kwargs)
    except TypeError:
        return func(kwargs["query"])


def _call_web_search(func: Callable[..., Any], **kwargs: Any) -> Any:
    try:
        return func(**kwargs)
    except TypeError:
        return func(kwargs["query"])


def _call_fetch(func: Callable[..., str], *, url: str, timeout_seconds: int) -> str:
    try:
        return func(url, timeout_seconds=timeout_seconds)
    except TypeError:
        return func(url)


def _normalise_maps_response(raw_response: Any) -> dict[str, Any]:
    if isinstance(raw_response, list):
        return {"places": raw_response}
    if isinstance(raw_response, dict):
        response = dict(raw_response)
        response.setdefault("places", [])
        return response
    return {"places": []}


def _normalise_web_response(raw_response: Any) -> dict[str, Any]:
    if isinstance(raw_response, dict):
        response = dict(raw_response)
        response.setdefault("organic", [])
        return response
    return {"organic": []}


def _place_name(place: dict[str, Any]) -> str:
    return str(place.get("title") or place.get("name") or "").strip()


def _dedupe_keys_for_place(place: dict[str, Any]) -> list[str]:
    keys: list[str] = []
    place_id = str(place.get("placeId") or "").strip()
    if place_id:
        keys.append(f"place_id:{place_id}")
    domain = _normalised_domain(str(place.get("website") or ""))
    if domain:
        keys.append(f"domain:{domain}")
    name_address = _normalised_name_address(_place_name(place), str(place.get("address") or ""))
    if name_address:
        keys.append(f"name_address:{name_address}")
    phone = _normalised_phone(str(place.get("phoneNumber") or place.get("phone") or ""))
    if phone:
        keys.append(f"phone:{phone}")
    if not keys:
        keys.append(f"fallback:{hashlib.sha1(str(place).encode('utf-8')).hexdigest()[:16]}")
    return list(dict.fromkeys(keys))


def _candidate_id_for_place(place: dict[str, Any]) -> str:
    basis = "|".join(_dedupe_keys_for_place(place))
    domain = _normalised_domain(str(place.get("website") or ""))
    slug_basis = domain.split(".")[0] if domain else _place_name(place)
    return f"wrm-replay-{slugify(slug_basis)[:40]}-{hashlib.sha1(basis.encode('utf-8')).hexdigest()[:8]}"


def _normalised_domain(url: str) -> str:
    parsed = urllib.parse.urlparse(str(url or "").strip())
    return parsed.netloc.lower().removeprefix("www.")


def _normalised_phone(phone: str) -> str:
    return "".join(ch for ch in str(phone or "") if ch.isdigit())


def _normalised_name_address(name: str, address: str) -> str:
    cleaned_name = " ".join(str(name or "").lower().split())
    cleaned_address = " ".join(str(address or "").lower().split())
    if not cleaned_name or not cleaned_address:
        return ""
    return f"{cleaned_name}|{cleaned_address}"


def _blocked_capture_link(link: str) -> bool:
    parsed = urllib.parse.urlparse(str(link or ""))
    host = parsed.netloc.lower().removeprefix("www.")
    return any(domain in host for domain in (
        "instagram.com",
        "facebook.com",
        "twitter.com",
        "x.com",
        "youtube.com",
        "tiktok.com",
        "pinterest.com",
    ))


def _collection_strata(jobs: list[dict[str, str]]) -> list[dict[str, str]]:
    return [
        {
            "city": job["city"],
            "category": job["category"],
            "job_id": job["job_id"],
            "purpose": job["purpose"],
            "expected_friction": job["expected_friction"],
        }
        for job in jobs
    ]
